DOTMATRIX_SEG1: .equ $4200
DOTMATRIX_SEG1_COMMAND: .EQU DOTMATRIX_SEG1 + $00 ; Command register
DOTMATRIX_SEG1_DATA:    .EQU DOTMATRIX_SEG1 + $01 ; Data register

DOTMATRIX_SEG2: .equ $4400
DOTMATRIX_SEG2_COMMAND: .EQU DOTMATRIX_SEG2 + $00 ; Command register
DOTMATRIX_SEG2_DATA:    .EQU DOTMATRIX_SEG2 + $01 ; Data register