DOTMATRIX_SEG1 = $4200
DOTMATRIX_SEG1_COMMAND = DOTMATRIX_SEG1 + $00 ; Command register
DOTMATRIX_SEG1_DATA = DOTMATRIX_SEG1 + $01 ; Data register

DOTMATRIX_SEG2 = $4400
DOTMATRIX_SEG2_COMMAND = DOTMATRIX_SEG2 + $00 ; Command register
DOTMATRIX_SEG2_DATA = DOTMATRIX_SEG2 + $01 ; Data register